services:
  frontend:
    build:
      context: frontend
    env_file:
      - frontend/.env
    volumes:
      - frontend:/app/frontend/dist

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: weblarek
    volumes:
      - ./_volume/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - db:/data/db
    networks:
      - internal

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo-express-data:/var/lib/mongo-express/data
    networks:
      - internal

  backend:
    restart: unless-stopped
    build:
      context: backend
    env_file:
      - backend/.env
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    ports:
      - 3000:3000
    networks:
      - internal
    depends_on:
      - mongo

  server:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  frontend:
  public:
  db:
  mongo-express-data:

networks:
  internal: